import type { Metadata } from 'next';
import { Plus_Jakarta_Sans, Inter } from 'next/font/google';
import './globals.css';
import Navbar from './_Components/Navbar/Navbar';
import { ThemeProvider } from './context/ThemeContext';
import ReactQueryProvider from './_Components/ReactQueryProvider/ReactQueryProvider';
import { Toaster } from 'react-hot-toast';

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-plus-jakarta-sans',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${plusJakartaSans.variable} ${inter.variable}`}
    >
      <ThemeProvider>
        <body className="dark:bg-dark-bg-primary bg-light-bg-primary mt-20 md:mt-32 lg:mt-0">
          <header>
            <Navbar />
          </header>
          <Toaster />
          <ReactQueryProvider>
            <main>{children}</main>
          </ReactQueryProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
